### ISSUE TITLE
`figwheel-sidecar.core/topo-sort` invalid comparison function

### ISSUE THREAD

**Issue by sfnelson** [bhauman/lein-figwheel#118]
We're getting exceptions from figwheel when a browser attaches to figwheel the first time:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeLo (TimSort.java:773)
    java.util.TimSort.mergeAt (TimSort.java:510)
    java.util.TimSort.mergeCollapse (TimSort.java:435)
    java.util.TimSort.sort (TimSort.java:241)
    java.util.Arrays.sort (Arrays.java:1438)
    clojure.core$sort.invoke (core.clj:2829)
    figwheel_sidecar.core$topo_sort.invoke (core.clj:289)
    figwheel_sidecar.core$expand_to_all_ns.invoke (core.clj:306)
    figwheel_sidecar.core$notify_cljs_ns_changes.invoke (core.clj:352)
    figwheel_sidecar.core$check_for_changes.invoke (core.clj:376)
    figwheel_sidecar.auto_builder$check_changes.invoke (auto_builder.clj:43)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$partial$fn__4228.doInvoke (core.clj:2468)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojurescript_build.auto$after$fn__16065.invoke (auto.clj:65)
    clojurescript_build.auto$after$fn__16065.invoke (auto.clj:64)
    clojurescript_build.auto$error$fn__16068.invoke (auto.clj:71)
    clojurescript_build.auto$before$fn__16062.invoke (auto.clj:60)
    clojurescript_build.auto$make_conditional_builder$fn__16080.invoke (auto.clj:103)
    clojure.core$mapv$fn__6311.invoke (core.clj:6353)
    clojure.lang.ArrayChunk.reduce (ArrayChunk.java:63)
    clojure.core.protocols/fn (protocols.clj:98)
    clojure.core.protocols$fn__6057$G__6052__6066.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:60)
    clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6289)
    clojure.core$mapv.invoke (core.clj:6353)
```

**Comment by bhauman** [comment]
I'll take a look at this today.

**Comment by bhauman** [comment]
I'm going to need more information here.  What is your environment? What configuration are you using?

**Comment by thefloweringash** [comment]
I added instrumentation and reproduced issue, the resulting graph formed by the comparison result in `topo-compare` contains a cycle. I've styled the `-1` edges as solid, and the default `1` edges as dotted. Note that the cycle arises entirely from dotted edges. The cycle is m13 -> m2 -> m1 -> m9 -> m8 -> m42 -> m16 -> m14 -> m13.

![topo-bug-graph](https://cloud.githubusercontent.com/assets/42933/7014795/8e50ab30-dd1d-11e4-909b-73ac8d3da6cb.png)

I don't think the implementation of `topo-compare` / `topo-sort` is a topological sort. Consider the diamond case where `a -> b`, `a -> c`, `b -> d`, `c -> d`. The `topo-compare` function will say that `b < c` and `c < b`, since they have no relation and the default is the same.

**Comment by bhauman** [comment]
I'd really love to see a minimal case for this issue.  I haven't been able to reproduce it.

Version numbers for cljs and Figwheel would be very helpful.

**Comment by thefloweringash** [comment]
Our project is relatively large and the error is intermittent. I've been triggering it by switching branches. I don't know if I'll be able to find a minimal case soon.

lein-figwheel: 0.2.5
clojurescript: 0.0-3126

**Comment by bhauman** [comment]
Oh, Figwheel, cljsbuild, etc.  aren't built to withstand the race conditions caused by switching branches especially in a large project.

Switching branches under autobuild is not supported.

**Comment by thefloweringash** [comment]
Switching branches was an example reproduction. We also see this from running cljx.

The `topo-sort` function uses `topo-compare` as a Java `Comparator`. The Java `Comparator` interface requires 

> The implementor must ensure that sgn(compare(x, y)) == -sgn(compare(y, x)) for all x and y

When given two modules with no relationship, `topo-compare` will always return 1, which violates the previous requirement and causes the exception.

Here is a synthetic example of this. The structure is like a "main" namespace including a large number of unrelated modules. We need at least 32 to cause TimSort to use merge sort.

```clojure
(defn shuffle-rand
  "Return a random permutation of coll"
  {:added  "1.2"
   :static true}
  [^java.util.Collection coll random]
  (let [al (java.util.ArrayList. coll)]
    (java.util.Collections/shuffle al random)
    (clojure.lang.RT/vector (.toArray al))))

(deftest test-topo-sort
  (let [all-modules (shuffle-rand (range 64) (java.util.Random. 2))]
    (binding [*transitive-dep-fn* {0 (set (range 1 64))}]
      (topo-sort all-modules))))
```

The current implementation attempts to make a total ordering from a partial ordering by arbitrarily assigning an ordering to unrelated pairs, and will happily produce a contradiction.

It should be easy to fix this by using `cljs-topo-sort` in place of `topo-sort`:

```clojure
(deftest test-cljs-topo-sort
  (let [all-modules (shuffle-rand (range 64) (java.util.Random. 2))
        deps {0 (set (range 1 64))}]
    (cljs-topo-sort :root (assoc deps
                            :root (set all-modules)))))
```

**Comment by bhauman** [comment]
OK gotcha,

I really appreciate you taking the time to investigate this and explain it to me. I'll look into it further.

**Comment by bhauman** [comment]
I redefined topo-compare to this

```
(defn topo-compare [nm nm2]
  (cond
    (= nm nm2) 0
    (get (*transitive-dep-fn* nm) nm2) -1
    (get (*transitive-dep-fn* nm2) nm) 1    
    :else 0))
```
https://github.com/bhauman/lein-figwheel/commit/69b3a7054983d508fa53870e738ba11bc8360beb

And it appears to be working great. The semantics of topo-sort and cljs-topo-sort are pretty different.  One sorts the given namespaces, the other expands to all the dependencies.

Thanks again for your work on this. Big error on my part.  I really need to simplify this now that there is a `:recompile-dependents` flag.

**Comment by bhauman** [comment]
I have just deployed this fix in 0.2.6

**Comment by sfnelson** [comment]
Thanks for your work on this issue. Unfortunately, your change still does not constitute a correct topo-sort because it still violates the `compare` contract, abet in a more subtle way:

> ensure that compare(x, y)==0 implies that sgn(compare(x, z))==sgn(compare(y, z)) for all z
> -- <cite>[Java API Specification][1]</cite>

Your implementation of topo-compare does not ensure this property. Consider the following graph:
![compare](https://cloud.githubusercontent.com/assets/325974/7103446/24dc68b4-e0fc-11e4-9aaf-220da84da4c3.png)

```
(topo-compare x y) => 0
(topo-compare x z) => 0
(topo-compare y z) => -1
```

As you can see, this leads to a contradiction.

The root problem with your approach is that you're trying to construct a total ordering from a partial ordering using only local information. This is just not possible, a total ordering has strictly more information than a partial ordering so you need to make decisions to break ties. This adds information to the system, and you need to make that decision available to the rest of the algorithm so it can make consistent decisions, otherwise you're going to get contradictions. This is why topo-sort is traditionally solved using greedy algorithms -- every time the algorithm makes a judgement it records that judgement so later steps can use it.

Topo-sort is a reasonably difficult problem but it's also a very well known one and there are lots of existing solutions. I suggest that rather than rolling your own you use an off-the-shelf solution.

`cljs-topo-sort` is one such existing solution -- it doesn't just expand to all the dependencies, it also returns them in topological order. You can use this to your advantage by creating a 'fake' node that depends on all the files that have changed, then calling cljs-topo-sort. This will return all the files reachable from your changed files in topological order. You can then filter the result for changed files.

If you're still not clear on the problem I'd be happy to create a pull request.

[1]:https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#compare-T-T-

**Comment by bhauman** [comment]
OK I get it.  I have been busy and have been focusing on what I expected the graphs of "normal" applications to be. This was an assumption that works for incremental changes on simpler projects.

I will get this fixed for the next release. Actually working on it this evening.

**Comment by bhauman** [comment]
I just pushed the fix for this.  This code should be faster as well.

https://github.com/bhauman/lein-figwheel/commit/4cf81722d7328ae81e140ad2c1815365c0f3082c

I'm going to push out a snapshot release tomorrow.

**Comment by sfnelson** [comment]
Looks reasonable to me.

**Comment by bhauman** [comment]
Just pushed 0.2.7-SNAPSHOT if you want to try this fix early.

**Comment by sfnelson** [comment]
It would be great to have a release with this fix.

**Comment by bhauman** [comment]
Just released 0.2.7. Gonna close for now this let me know if it isn't working, I'll reopen.
