### ISSUE TITLE
Can't get a REPL: missing connect.cljs

### ISSUE THREAD

**Issue by GoranM** [bhauman/lein-figwheel#137]
I'm trying to follow along with the [basic om tutorial](https://github.com/omcljs/om/wiki/Basic-Tutorial). I can get to the point where I see "Hello world" displayed in the browser, but I don't get a REPL prompt.

figwheel_server.log contains this:

```
Figwheel: focusing on build-ids (dev)
[0mCompiling "resources/public/js/compiled/om_tut.js" from ["src"]...
[31mCompiling "resources/public/js/compiled/om_tut.js" failed.[0m
java.io.FileNotFoundException: target/figwheel_temp/dev/figwheel/connect.cljs (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2)
    java.io.FileOutputStream.open (FileOutputStream.java:270)
    java.io.FileOutputStream.<init> (FileOutputStream.java:213)
    clojure.java.io/fn (io.clj:230)
    clojure.java.io$fn__8641$G__8604__8648.invoke (io.clj:69)
    clojure.java.io/fn (io.clj:166)
    clojure.java.io$fn__8654$G__8608__8661.invoke (io.clj:69)
    clojure.java.io$writer.doInvoke (io.clj:119)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    figwheel_sidecar.auto_builder$create_connect_script_BANG_.invoke (auto_builder.clj:130)
    figwheel_sidecar.auto_builder$create_connect_script_if_needed_BANG_.invoke (auto_builder.clj:142)
    figwheel_sidecar.auto_builder$add_connect_script_BANG_.invoke (auto_builder.clj:147)
    figwheel_sidecar.auto_builder$insert_figwheel_connect_script$fn__17455.invoke (auto_builder.clj:164)
    figwheel_sidecar.auto_builder$warning$fn__17421.invoke (auto_builder.clj:73)
    clojurescript_build.auto$time_build$fn__17217.invoke (auto.clj:55)
    clojurescript_build.auto$after$fn__17223.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17223.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17223.invoke (auto.clj:64)
    clojurescript_build.auto$error$fn__17226.invoke (auto.clj:71)
    clojurescript_build.auto$before$fn__17220.invoke (auto.clj:60)
    clojurescript_build.auto$make_conditional_builder$fn__17238.invoke (auto.clj:103)
    clojure.core$mapv$fn__6311.invoke (core.clj:6353)
    clojure.lang.ArrayChunk.reduce (ArrayChunk.java:58)
    clojure.core.protocols/fn (protocols.clj:98)
    clojure.core.protocols$fn__6057$G__6052__6066.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:60)
    clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6289)
    clojure.core$mapv.invoke (core.clj:6353)
```

So it seems to be looking for connect.cljs, which isn't there.

My lein version:

```
Leiningen 2.5.1 on Java 1.8.0_45 OpenJDK Server VM
```

My project.clj:

```clojure
(defproject om-tut "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-3165"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [sablono "0.3.4"]
                 [org.omcljs/om "0.8.8"]]

  :plugins [[lein-cljsbuild "1.0.5"]
            [lein-figwheel "0.2.8"]]

  :source-paths ["src"]

  :clean-targets ^{:protect false} ["resources/public/js/compiled" "target"]
  
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              
              :figwheel { :on-jsload "om-tut.core/on-js-reload" }

              :compiler {:main om-tut.core
                         :asset-path "js/compiled/out"
                         :output-to "resources/public/js/compiled/om_tut.js"
                         :output-dir "resources/public/js/compiled/out"
                         :optimizations :none
                         :source-map true
                         :source-map-timestamp true
                         :cache-analysis true }}
             {:id "min"
              :source-paths ["src"]
              :compiler {:output-to "resources/public/js/compiled/om_tut.js"
                         :main om-tut.core                         
                         :optimizations :advanced
                         :pretty-print false}}]}

  :figwheel {
             ;; :http-server-root "public" ;; default and assumes "resources" 
             ;; :server-port 3449 ;; default
             :css-dirs ["resources/public/css"] ;; watch and update CSS

             ;; Start an nREPL server into the running figwheel process
             ;; :nrepl-port 7888

             ;; Server Ring Handler (optional)
             ;; if you want to embed a ring handler into the figwheel http-kit
             ;; server, this is for simple ring servers, if this
             ;; doesn't work for you just run your own server :)
             ;; :ring-handler hello_world.server/handler

             ;; To be able to open files in your editor from the heads up display
             ;; you will need to put a script on your path.
             ;; that script will have to take a file path and a line number
             ;; ie. in  ~/bin/myfile-opener
             ;; #! /bin/sh
             ;; emacsclient -n +$2 $1
             ;;
             ;; :open-file-command "myfile-opener"

             ;; if you want to disable the REPL
             ;; :repl false

             ;; to configure a different figwheel logfile path
             ;; :server-logfile "tmp/logs/figwheel-logfile.log" 
             })
```

**Comment by danielstreit** [comment]
I'm having the same issue... following the tutorial, but repl does not start and changes to file only reflected after exiting and rerunning `lein figwheel`

**Comment by kahunamoore** [comment]
+1 I'm seeing this too.

Here are my steps to reproduce:

1) lein new figwheel hello-world
2) cd hello-world
3) edit project.clj to add :figwheel true to the :dev build
4) lein figwheel
5) observe: error in figwheel_server.log (connect.cljs file not found)
6) observe: new directory created under target called target/figwheel_temp/dev

I can help debug the problem on my end if I knew what code in figwheel is supposed to create that file - I searched the figwheel repository on github but the only instance of that string is the call to open that file, line 86 of file sidecar/src/figwheel_sidecar/auto_builder.clj:

(str (connect-script-temp-dir build) "/figwheel/connect.cljs"))

Note that this path does not match the one in the logfile from the failure. I could not find any file in my project directory called connect.cljs.

Does another library write that file? Sidecar perhaps?

**Comment by bhauman** [comment]
Darn! Fixing this right now.

**Comment by bhauman** [comment]
I released a new version of figwheel yesterday.  I updated the template as well.  

I just reverted the template. It should be working now.

**Comment by bhauman** [comment]
Just deployed 0.2.9

**Comment by zentrope** [comment]
Even with the latest 0.2.9, I still don't see any `target/figwheel_temp` directory, and so my browser logs:

    [Error] goog.require could not find: figwheel.connect require (base.js, line 466)...
    [Error] Error: goog.require could not find: figwheel.connect...

I don't see any evidence of the generated scripts at all. I always set `:repl false`.

Set up:

```clojure
  :cljsbuild
  {:builds [{:id "dev"
             :source-paths ["src/cljs" #_"src/dev"]
             :compiler {:output-to "resources/public/main.js"
                        :output-dir "resources/public/out"
                        :main startrak.main
                        :optimizations :none
                        :asset-path "out"
                        :source-map true
                        :source-map-timestamp true
                        :figwheel {:on-jsload "startrak.main/reload"
                                   ;; :websocket-url "ws://localhost:3449/figwheel-ws"
                                   :websocket-url "localhost"
                                   :heads-up-display false}}} ]}

  :figwheel {:http-server-root "public"
             :server-port 3449
             :repl false
             :css-dirs ["resources/public"]}
```

It's a bit unclear in the documentation whether or not the injection works if you don't _just_ use `:figwheel true`.

**Comment by bhauman** [comment]
Yes any `:figwheel` present in the build config will cause client injection.

Can you give me a minimal reproduction using `lein new fighweel hello-world`?

**Comment by bhauman** [comment]
Did you see anything in the `figwheel_server.log`?

**Comment by zentrope** [comment]
Here's what I see:

<pre>
= git:master > lein clean ; lein figwheel
Retrieving lein-figwheel/lein-figwheel/0.2.9/lein-figwheel-0.2.9.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.2.9/figwheel-sidecar-0.2.9.pom from clojars
Retrieving figwheel/figwheel/0.2.9/figwheel-0.2.9.pom from clojars
Retrieving lein-figwheel/lein-figwheel/0.2.9/lein-figwheel-0.2.9.jar from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.2.9/figwheel-sidecar-0.2.9.jar from clojars
Retrieving figwheel/figwheel/0.2.9/figwheel-0.2.9.jar from clojars
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "resources/public/main.js" from ["src/cljs"]...
Successfully compiled "resources/public/main.js" in 7.82 seconds.
Figwheel: focusing on build-ids (dev)
Started Figwheel autobuilder
Compiling "resources/public/main.js" from ["src/cljs"]...
Successfully compiled "resources/public/main.js" in 0.082 seconds.
notifying browser that file changed:  resources/public/out/goog/deps.js
notifying browser that file changed:  resources/public/out/cljs_deps.js
notifying browser that file changed:  /startrak/lib/utils.js
notifying browser that file changed:  /startrak/component/projects.js
notifying browser that file changed:  /startrak/component/masthead.js
notifying browser that file changed:  /startrak/component/login.js
notifying browser that file changed:  /startrak/component/status.js
notifying browser that file changed:  /startrak/lib/socket.js
notifying browser that file changed:  /startrak/component/users.js
notifying browser that file changed:  /startrak/component/issue.js
notifying browser that file changed:  /startrak/main.js
notifying browser that file changed:  /startrak/component/issues.js
</pre>

**Comment by zentrope** [comment]
I wonder if it's because I have `:figwheel` under `:compiler`, while you have it as a peer to compiler?

**Comment by zentrope** [comment]
Okay, I think I figured out the problem.

On the README, you have:

```clojure
:cljsbuild {
  :builds [ { :id "example" 
              :source-paths ["src/"]
              :compiler {  :main "example.core"
                           :asset-path "js/out"
                           :figwheel { :on-jsload "example.core/reload-hook" }
                           :output-to "resources/public/js/compiled/example.js"
                           :output-dir "resources/public/js/compiled/out"
                           :externs ["resources/public/js/externs/jquery-1.9.js"]
                           :optimizations :none
                           :source-map true
                           :source-map-timestamp true } } ]}
```

But in the template, you have:

```clojure
  
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              
              :figwheel { :on-jsload "hello-world.core/on-js-reload" }

              :compiler {:main hello-world.core
                         :asset-path "js/compiled/out"
                         :output-to "resources/public/js/compiled/hello_world.js"
                         :output-dir "resources/public/js/compiled/out"
                         :optimizations :none
                         :source-map true
                         :source-map-timestamp true
                         :cache-analysis true }}
             {:id "min"
              :source-paths ["src"]
              :compiler {:output-to "resources/public/js/compiled/hello_world.js"
                         :main hello-world.core                         
                         :optimizations :advanced
                         :pretty-print false}}]}
```

Notice the different location of `:figwheel` in the cljsbuild definition. That's why the script wasn't generated. ;) Works in the template version.

Phew!

**Comment by bhauman** [comment]
yes just fixed this

**Comment by danielstreit** [comment]
Thanks for the quick fix @bhauman!

**Comment by kahunamoore** [comment]
I just tried the same steps again. The lein template generates a project with figwheel 0.2.8. I tried changing the project.clj to point to figwheel 0.2.9 but that didn't change the behavior.

The server log file contains a bunch of warnings like this:

WARNING: Use of undeclared Var cljs.core/dec at line 657 resources/public/js/compiled/out/cljs/core/async.cljs

... for most of cljs.core.* lots and lots of them.

Then I updated the version of clojurescript to the latest 3122 and rebuilt and was then able to get a figwheel repl. I don't know exactly what combination of those things fixed it but I think just the template needs to be updated to the latest.

I see on clojars that the figwheel template is up to version 3.0.1 and when I look on github the template project sources show a dependency on figwheel 0.2.9 . Is there some way I can force the updated/newer template be downloaded/used? What am I doing wrong?

Thanks!

**Comment by bhauman** [comment]
I don't know why you ended up generating the older template.  I will redeploy the template again this morning to make sure.

The template version number is now out of sync with the Figwheel release number. I have a plan to keep them in sync in the future.

**Comment by ghost** [comment]
@GoranM shame on you for selling yourself as a cheap slave. Shame on you for saying that disgusting and racist and arrogant word before the name "frev", in your BGE outline shader tutroial. You are a big worthless loser Goran. DEATH to everyone who uses those words. DEATH to "univeristies". DEATH to the disgusting and garbage so called "health sector". DEATH TO LOSERS WHO USE STUPID "TITLES". SHAME ON YOU @GoranM
