### ISSUE TITLE
bleeding edge startup failure

### ISSUE THREAD

**Issue by cemerick** [bhauman/lein-figwheel#516]
Using `9b289` of figwheel with `7de56` of ClojureScript is a no-go at the moment:

```
IllegalArgumentException Key must be integer  clojure.lang.APersistentVector.assoc (APersistentVector.java:345)
java.lang.IllegalArgumentException: Key must be integer
       APersistentVector.java:345 clojure.lang.APersistentVector.assoc
        APersistentVector.java:18 clojure.lang.APersistentVector.assoc
                      RT.java:807 clojure.lang.RT.assoc
                     core.clj:191 clojure.core/assoc
                    core.clj:6060 clojure.core/update-in[fn]
                    core.clj:6061 clojure.core/update-in
                    core.clj:6047 clojure.core/update-in
                  RestFn.java:445 clojure.lang.RestFn.invoke
        exception_parsing.clj:314 figwheel-sidecar.cljs-utils.exception-parsing/exception-data->display-data[fn]
                    core.clj:2721 clojure.core/map[fn]
                  LazySeq.java:40 clojure.lang.LazySeq.sval
                  LazySeq.java:49 clojure.lang.LazySeq.seq
                      RT.java:525 clojure.lang.RT.seq
                     core.clj:137 clojure.core/seq
                    core.clj:2712 clojure.core/map[fn]
                  LazySeq.java:40 clojure.lang.LazySeq.sval
                  LazySeq.java:49 clojure.lang.LazySeq.seq
                      RT.java:525 clojure.lang.RT.seq
                     core.clj:137 clojure.core/seq
                 protocols.clj:24 clojure.core.protocols/seq-reduce
                 protocols.clj:75 clojure.core.protocols/fn
                 protocols.clj:75 clojure.core.protocols/fn
                 protocols.clj:13 clojure.core.protocols/fn[fn]
                    core.clj:6693 clojure.core/reduce
                    core.clj:6679 clojure.core/reduce
        exception_parsing.clj:410 figwheel-sidecar.cljs-utils.exception-parsing/formatted-exception-display-str
        exception_parsing.clj:399 figwheel-sidecar.cljs-utils.exception-parsing/formatted-exception-display-str
        exception_parsing.clj:441 figwheel-sidecar.cljs-utils.exception-parsing/print-exception
        exception_parsing.clj:438 figwheel-sidecar.cljs-utils.exception-parsing/print-exception
        exception_parsing.clj:439 figwheel-sidecar.cljs-utils.exception-parsing/print-exception
        exception_parsing.clj:438 figwheel-sidecar.cljs-utils.exception-parsing/print-exception
           cljs_autobuild.clj:187 figwheel-sidecar.components.cljs-autobuild/catch-print-hook[fn]
           cljs_autobuild.clj:141 figwheel-sidecar.components.cljs-autobuild/open-urls-hook[fn]
           stamp_and_clean.clj:66 figwheel-sidecar.build-middleware.stamp-and-clean/hook[fn]
            cljs_autobuild.clj:79 figwheel-sidecar.components.cljs-autobuild/color-output[fn]
           cljs_autobuild.clj:255 figwheel-sidecar.components.cljs-autobuild/figwheel-sidecar.components.cljs-autobuild.CLJSAutobuild
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25262__25275.invoke
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25261__25278.invoke
                     Var.java:379 clojure.lang.Var.invoke
                     AFn.java:154 clojure.lang.AFn.applyToHelper
                     Var.java:700 clojure.lang.Var.applyTo
                     core.clj:653 clojure.core/apply
                     core.clj:646 clojure.core/apply
               component.cljc:117 com.stuartsierra.component$try_action.invokeStatic
               component.cljc:116 com.stuartsierra.component$try_action.invoke
               component.cljc:139 com.stuartsierra.component$update_system$fn__25331.invoke
                ArraySeq.java:114 clojure.lang.ArraySeq.reduce
                    core.clj:6696 clojure.core/reduce
                    core.clj:6679 clojure.core/reduce
               component.cljc:135 com.stuartsierra.component$update_system.invokeStatic
               component.cljc:129 com.stuartsierra.component$update_system.doInvoke
                  RestFn.java:445 clojure.lang.RestFn.invoke
               component.cljc:163 com.stuartsierra.component$start_system.invokeStatic
               component.cljc:155 com.stuartsierra.component$start_system.invoke
               component.cljc:161 com.stuartsierra.component$start_system.invokeStatic
               component.cljc:155 com.stuartsierra.component$start_system.invoke
               component.cljc:178 com.stuartsierra.component.SystemMap.start
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25262__25275.invoke
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25261__25278.invoke
                     Atom.java:37 clojure.lang.Atom.swap
                    core.clj:2335 clojure.core/swap!
                    core.clj:2328 clojure.core/swap!
                   system.clj:118 figwheel-sidecar.system/figwheel-sidecar.system.FigwheelSystem
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25262__25275.invoke
                 component.cljc:5 com.stuartsierra.component$eval25272$fn__25273$G__25261__25278.invoke
                     Var.java:379 clojure.lang.Var.invoke
                     AFn.java:154 clojure.lang.AFn.applyToHelper
                     Var.java:700 clojure.lang.Var.applyTo
                     core.clj:653 clojure.core/apply
                     core.clj:646 clojure.core/apply
               component.cljc:117 com.stuartsierra.component$try_action.invokeStatic
               component.cljc:116 com.stuartsierra.component$try_action.invoke
               component.cljc:139 com.stuartsierra.component$update_system$fn__25331.invoke
                ArraySeq.java:109 clojure.lang.ArraySeq.reduce
                    core.clj:6696 clojure.core/reduce
                    core.clj:6679 clojure.core/reduce
               component.cljc:135 com.stuartsierra.component$update_system.invokeStatic
               component.cljc:129 com.stuartsierra.component$update_system.doInvoke
                  RestFn.java:445 clojure.lang.RestFn.invoke
               component.cljc:163 com.stuartsierra.component$start_system.invokeStatic
               component.cljc:155 com.stuartsierra.component$start_system.invoke
               component.cljc:161 com.stuartsierra.component$start_system.invokeStatic
               component.cljc:155 com.stuartsierra.component$start_system.invoke
               component.cljc:178 com.stuartsierra.component.SystemMap.start
                   system.clj:658 figwheel-sidecar.system/start-figwheel-system[fn]
                   system.clj:644 figwheel-sidecar.system/dispatch-system-component-errors
                   system.clj:642 figwheel-sidecar.system/dispatch-system-component-errors
                   system.clj:658 figwheel-sidecar.system/start-figwheel-system
                   system.clj:656 figwheel-sidecar.system/start-figwheel-system
                   system.clj:693 figwheel-sidecar.system/start-figwheel!*
                   system.clj:679 figwheel-sidecar.system/start-figwheel!*
                     AFn.java:156 clojure.lang.AFn.applyToHelper
                     AFn.java:144 clojure.lang.AFn.applyTo
                     core.clj:651 clojure.core/apply
                     core.clj:646 clojure.core/apply
                   system.clj:737 figwheel-sidecar.system/start-figwheel!
                   system.clj:695 figwheel-sidecar.system/start-figwheel!
                  RestFn.java:397 clojure.lang.RestFn.invoke
                      user.clj:16 user/start-figwheel![fn]
```

FWIW, the codebase builds and runs well when invoked via cljsbuild. Figwheel config is what I was using for months with `0.5.4-7` and ClojureScript `1.9.89`:

```clojure
{:id "dev"
 :source-paths ["toolkit/src" "src/cljc"]

 ;; the presence of a :figwheel configuration here
 ;; will cause figwheel to inject the figwheel client
 ;; into your build
 :figwheel {:on-jsload "xxx/on-js-reload"}

 :compiler {:main xxx.yyy
            :asset-path "/js/"
            :output-to "target/classes/public/js/viewer.js"
            :output-dir "target/classes/public/js/"
            :source-map-timestamp true
            :infer-externs true
            ;; To console.log CLJS data-structures make sure you enable devtools in Chrome
            ;; https://github.com/binaryage/cljs-devtools
            :preloads [devtools.preload]}}
```

Maybe I'm missing something?

**Comment by cemerick** [comment]
Not sure if it helps or just confuses things more, but using the aforementioned `0.5.4-7` with ClojureScript HEAD (`1.9.440` here) yields a different error:

```
Failed to compile "target/classes/public/js/viewer.js" in 29.473 seconds.
----  Exception    ----

  G:\dev\xxxx\foo.js is not a relative path

----  Exception Stack Trace  ----

java.lang.IllegalArgumentException: G:\dev\xxxx\foo.js is not a relative path
 at clojure.java.io$as_relative_path.invokeStatic (io.clj:414)
    clojure.java.io$file.invokeStatic (io.clj:426)
    clojure.java.io$file.invoke (io.clj:418)
    cljs.closure$write_javascript.invokeStatic (closure.clj:1594)
    cljs.closure$write_javascript.invoke (closure.clj:1587)
    cljs.closure$source_on_disk.invokeStatic (closure.clj:1633)
    cljs.closure$source_on_disk.invoke (closure.clj:1628)
    cljs.closure$output_unoptimized$fn__6440.invoke (closure.clj:1671)
    clojure.core$map$fn__6623.invoke (core.clj:2721)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:525)
    clojure.core$seq__6165.invokeStatic (core.clj:137)
    clojure.core$filter$fn__6650.invoke (core.clj:2775)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:525)
    clojure.core$seq__6165.invokeStatic (core.clj:137)
    clojure.core$map$fn__6623.invoke (core.clj:2712)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:703)
    clojure.core$next__6149.invokeStatic (core.clj:64)
    clojure.core$str$fn__6228.invoke (core.clj:551)
    clojure.core$str.invokeStatic (core.clj:549)
    clojure.core$str.doInvoke (core.clj:538)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:651)
    clojure.core$apply.invoke (core.clj:646)
    cljs.closure$deps_file.invokeStatic (closure.clj:1367)
    cljs.closure$deps_file.invoke (closure.clj:1364)
    cljs.closure$output_deps_file.invokeStatic (closure.clj:1387)
    cljs.closure$output_deps_file.invoke (closure.clj:1386)
    cljs.closure$output_unoptimized.invokeStatic (closure.clj:1679)
    cljs.closure$output_unoptimized.doInvoke (closure.clj:1662)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:653)
    clojure.core$apply.invoke (core.clj:646)
    cljs.closure$build.invokeStatic (closure.clj:2119)
    cljs.closure$build.invoke (closure.clj:2009)
    cljs.build.api$build.invokeStatic (api.clj:200)
    cljs.build.api$build.invoke (api.clj:187)
    figwheel_sidecar.components.cljs_autobuild$cljs_build.invokeStatic (cljs_autobuild.clj:28)
```

`foo.js` above is an extern. Very strange error, I've never seen that one before either.

**Comment by bhauman** [comment]
Hmmm interesting, there is a failure in exception parsing, maybe the shape of exception data has changed.  I'll have to throw some exceptions to find out.

But get rid of the exception and you won't have a problem ...

**Comment by bhauman** [comment]
hey try this:
figwheel_sidecar/cljs_utils/exception-parsing line 317
                 (:exception-data exception)))
change it to this:
                 (flatten-exception (:exception-data exception))))

I'm sure this is the problem. It's my bug ...

**Comment by cemerick** [comment]
Figwheel does start up with that change. I am still left with the error that the previous rev of figwheel emits when used with the latest CLJS rev (`G:\dev\xxxx\foo.js is not a relative path` for a foreign lib). I did a little spelunking in `cljs.closure` etc without much of any conclusion; but lein-cljsbuild builds are succeeding, so it's a strange thing.

Any thought as to what might be causing this?

**Comment by bhauman** [comment]
It is a strange error. If figwheel starts then the figwheel cljs-repl should start (even if thing didn't compile) by just opening/refreshing the browser.

Try the (print-config) command in the figwheel repl

**Comment by bhauman** [comment]
I definitely looking like its' trying to write out the externs file.  Where is your externs file located with respect to your cljs source files?

The reason that I'm so hot on this is that I'd like to understand any problems that have been introduced by the new compiler changes this weekend while I have time off.

If you could send the :cljsbuild section of your project.clj that would be helpful.

**Comment by cemerick** [comment]
I've trimmed things down so I can more easily provide config info, etc.

Here's the cljsbuild config that works well:

```clojure
{"min" {:source-paths ["src" "toolkit/src"]
        :main xxx.yyy
        :compiler {:output-to "target/classes/public/js/viewer.js"
                   :main xxx.yyy
                   :optimizations :advanced
                   :pretty-print false
                   :infer-externs true
                   :language-in :ecmascript5}}}
```

Pretty vanilla, I think. More interesting/relevant is a project-local deps.cljs:

```clojure
{:foreign-libs [{:file "react-draggable/dist/react-draggable.js"
                 :file-min "react-draggable/dist/react-draggable.min.js"
                 :provides ["react-draggable"]
                 :requires ["cljsjs.react" "cljsjs.react.dom"]}]}
```

(I use this to pull in a js lib resolved by lein-npm.)

Just to restate the error:

```
----  Exception    ----

  G:\dev\pdfdata.io\main\node_modules\react-draggable\dist\react-draggable.js is not a relative path

----  Exception Stack Trace  ----

java.lang.IllegalArgumentException: G:\dev\pdfdata.io\main\node_modules\react-draggable\dist\react-draggable.js is not a relative path
 at clojure.java.io$as_relative_path.invokeStatic (io.clj:414)
    clojure.java.io$file.invokeStatic (io.clj:426)
    clojure.java.io$file.invoke (io.clj:418)
    cljs.closure$write_javascript.invokeStatic (closure.clj:1594)
```

When I instrument some of `cljs.closure`, I see that the foreign lib map has gained absolute-path URLs by the time `cljs.closure/write-javascript` passes it to `rel-output-path`:

```clojure
{:file "react-draggable/dist/react-draggable.js", :lines nil, :source-url nil, 
 :requires ["cljsjs.react" "cljsjs.react.dom"],
 :url-min #object[java.net.URL 0x20f212d4 "file:/G:/dev/pdfdata.io/main/node_modules/react-draggable/dist/react-draggable.min.js"], 
 :url #object[java.net.URL 0x1159783a "file:/G:/dev/pdfdata.io/main/node_modules/react-draggable/dist/react-draggable.js"], 
 :source-map nil, :provides ["react-draggable"], :foreign true, :file-min "react-draggable/dist/react-draggable.min.js"}
```

Hopefully that helps...

**Comment by cemerick** [comment]
FYI, same behaviour with the latest `1.9.456` CLJS release.

**Comment by bhauman** [comment]
And you are saying that when you use cljsbuild the instrumentation still shows a relative path?

**Comment by bhauman** [comment]
Also can I assume that you are sym linking to this file?

**Comment by cemerick** [comment]
No, the extern is coming out of `node_modules`, which I have in my `:resource-paths`.

**Comment by cemerick** [comment]
Hey @bhauman, I put together a minimal case reproducing this here:

https://github.com/cemerick/figwheel-516

I hope that helps!

**Comment by bhauman** [comment]
First of all thanks for the minimal case, it's super helpful.

But this all works for me ... which is unfortunate, as that kinda pegs this as a windows path problem.

Also I played around with the config around and tried to get this to break but no go.

Some things to try (if you haven't already):

Move the dev config to cljsbuild:
then try 
lein clean
lein cljsbuild once dev
lein clean
lein cljsbuild auto dev

and see if those work as well.

Another thing to try is: instead of referring to draggable on the resource path, refer to it by the project relative path.


PS: I noticed the strange inconsistent behavior on where the config is located and validation, I'm going to look into that.

**Comment by bhauman** [comment]
I strongly suspect that this is a compiler bug.

**Comment by cemerick** [comment]
I updated https://github.com/cemerick/figwheel-516 to add the figwheel config to the `:cljsbuild` options. `lein do clean, cljsbuild once dev` succeeds, and everything looks like it's where it should be. (Auto build also seems to work fine, not sure if you were implying they'd be different?)

AFAIK, project-root-relative paths stopped working some time ago, in preference to classpath-relative paths.

A windows path-related compiler bug makes a ton of sense, and I've now confirmed that figwheel works as expected in an (ubuntu) docker environment. The tricky thing is trying to pin it on the compiler as long as cljsbuild is working in a windows env.

I'll see what I can see later today with more cljs.closure digging...

**Comment by bhauman** [comment]
The really strange thing here is that the deps.cljs is pulled in by the compiler and never touched by figwheel.

Some strange env thing is happening.

Hmmmm the repl env is different 

Have you tried figwheel from the command line?  The latest few commits allow this without changing the config

**Comment by cemerick** [comment]
With just a couple minor tweaks to the repro config, my hopes were lifted when I saw that `lein do clean, figwheel` compiled things just fine, and I was able to get a page open auto-reloading code.

Unfortunately, doing the same thing in my real project fails with the same not-a-relative-path error.

It's completely weird to me that this would make a difference even in the simplified case though? Anyway, yeah, I'll have to really sit down with the compiler's path-handling stuff and see what's going on.

**Comment by bhauman** [comment]
It's gotta be the different env created in subproject. But it is strange.

I'm sure if you straight compile using the cljs.build.api you will get the same result from the lein repl.

**Comment by bhauman** [comment]
Oh wait ... `lein figwheel` fails in your regular project? I didn't get that, so darn weird.

**Comment by led** [comment]
I'm getting the same issue. Project is on OSX, latest figwheel, clojurescript. cljsbuild is fine, but if I compile using figwheel I get the error…

/x/y/z.js is not a relative path
at clojure.java.io$as_relative_path.invokeStatic (io.clj:414)"

Originally the lib was symlinked, so I moved it locally, still no joy. Tried using the URL for the lib, same error.

**Comment by bhauman** [comment]
Can you please make a minimal case?

**Comment by bhauman** [comment]
@cemerick 
I'm pretty sure this function 
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/util.cljc#L145

being called from here:
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L1593

Is what is failing for you.

`cljs.closure/rel-output-path` is returning the full path and that's whats causing `io/file` to throw that error.

The call to `(System/getProperty "user.dir")`  could be wonky based on your Env.

This really isn't the way to relativize a file anyway.

**Comment by cemerick** [comment]
Close, not quite.

The problematic commit is https://github.com/clojure/clojurescript/commit/97d2d61e78ce747d02d0e5b2ced706f6fb68ec4e

The fix (or, it works here) is https://github.com/cemerick/clojurescript/commit/495dd0d377daa649a17f58799e2a6a7a0d686363

@led: are you able to pull my commit above and build and test a local ClojureScript build to see if it resolves the problem for you, too?

**Comment by cemerick** [comment]
@bhauman that is to say, perhaps what you point out is a problem, too, but the change I landed on fixed things for me ;-P

**Comment by bhauman** [comment]
No I'm in agreement, I was saying that relative-name was failing.  I wasn't sure why.  Glad you found it!!

**Comment by led** [comment]
@cemerick, @bhauman : Yes, that works for me. Thanks for finding and fixing.

**Comment by bhauman** [comment]
@cemerick 

Also for your consideration
https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/utils.clj#L89

**Comment by cemerick** [comment]
Patch submitted: http://dev.clojure.org/jira/browse/CLJS-1927

**Comment by cemerick** [comment]
@bhauman sorry, what's this in relation to? Are you thinking that function is implicated in the problem here? It's not in any of the stack traces AFAICT.

**Comment by bhauman** [comment]
No sorry that is just a good cross platform javay way to get the relative path from a absolute-path url
which is what relative name is doing. 

Just a more robust way of doing it.

**Comment by bhauman** [comment]
@cemerick ^^^

**Comment by jiangts** [comment]
I'm also encountering this error on the latest ClojureScript 1.9.542/1.9.562 builds.

```
Failed to compile "resources/public/js/compiled/bug.js" in 13.753 seconds.
----  Exception    ----

  /bug/index.js is not a relative path
```

I've reproduced it from the figwheel template, and attached the failing case here:
https://github.com/jiangts/figwheel-516

Of note are the addition of `:libs ["src"]` to the compiler settings and me requiring a Closure style JS file from ClojureScript.

Currently have a hybrid CLJS/Closure JS application and would really like to use the new externs inference features of the newer CLJS compilers

**Comment by BerzinsU** [comment]
@jiangts Had similar issue. Solved by adding slash at the end of libs folder 
`:libs ["src/client-js"]`  ->` :libs ["src/client-js/"]`
Maybe this helps for you.

**Comment by markhepburn** [comment]
Just coming back to this -- I had a similar issue that I've just resolved, I wonder if it isn't related: https://dev.clojure.org/jira/browse/CLJS-2221

In my case, the issue was that in cmd.exe the "user.dir" property had a different case to that running under emacs (where the `default-directory` variable always has a lower-case drive letter for some reason), and the string substitution therefore fails.

**Comment by bhauman** [comment]
All of these issues have been located in the CLojureScript compiler so I'm going to call this issue closed for now.

**Comment by gtrak** [comment]
is #593 related?
